version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-docker
    build: 
      context: ./pipeline-jenkinsfile/
    ports:
      - 8080:8080
    volumes:
      - '$PWD/jenkins-home:/var/jenkins_home'
    networks:
      - net
    environment:
      - DOCKER_HOST=tcp://socat:2375
    links:
      - socat

  socat:
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "2375"
    networks:
      - net
  
  remote:
    container_name: remote
    image: remote-host
    build: 
      context: ./centos/
    volumes:
      - "$PWD/db-snap-upload.sh:/tmp/dump-script.sh"
    networks:
      - net

  do_host:
    platform: linux/amd64
    container_name: db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes: 
      - '$PWD/db_data:/var/lib/mysql'
    networks:
      - net

  web:
    container_name: web
    image: ansible-web
    build:
      context: ./jenkins-ansible/web/
    ports:
      - 3000:3000
    networks:
      - net
    depends_on:
      - remote

  git:
    #root1234
    container_name: git
    image: 'gitlab/gitlab-ce:latest'
    ports:
      - '8090:80'
      - '443:443'
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - net

networks:
  net: 
